name: Compile (Reusable)

on:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # If 'platform' input is empty, build all of these
        platform: ${{ inputs.platform != '' && fromJSON(inputs.platform) ||
                     fromJSON('["adam","apple2","c16","c64","coco","msdos"]') }}

    container:
      image: fozztexx/defoogi:1.4.0

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make -C clients/${{ matrix.platform }} disk

      - name: Upload artifact for ${{ matrix.platform }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: clients/${{ matrix.platform }}/dist/**
